{% set name = "hyram" %}
{% set version = "6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hyram-{{ version }}.tar.gz
  sha256: 80ec93279763319082e9709c62cbe8b821e222fb1f915215254a385bd0e37423

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - scipy
    - coolprop >=6.3
    - numpy

test:
  imports:
    - hyram
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://hyram.sandia.gov/
  summary: Hydrogen Plus Other Alternative Fuels Risk Assessment Models Python Package
  license: GPL-3.0-only
  license_file:
    - COPYING.txt

extra:
  recipe-maintainers:
    - EthanHecht
    - bdehrha
    - bliu1013
