{% set name = "hyram" %}
{% set version = "5.1.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hyram-{{ version }}.tar.gz
  sha256: b421dad2136eb873769a99190148df057a48dbfbd47c20ced9ade824f07165bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >3.6,<3.11
    - pip
  run:
    - python >3.6,<3.11
    - matplotlib-base
    - scipy
    - coolprop >=6.3
    - numpy

test:
  imports:
    - hyram
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hyram.sandia.gov/
  summary: Hydrogen Plus Other Alternative Fuels Risk Assessment Models Python Package
  license: GPL-3.0-only
  license_file:
    - hyram.egg-info/COPYING.txt

extra:
  recipe-maintainers:
    - EthanHecht
    - bdehrha
    - bliu1013
